apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloud-platform
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/Saikarthick11/production-cloud-deployment-platform.git
  destinations:
    - namespace: cloud-platform-gitops
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
